global:
  scrape_interval: 1s
  evaluation_interval: 1s

alerting:
  alertmanagers:
    - scheme: http
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: "prometheus"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["springboot:8080"]