import Android_studio from './assets/image/stacklogo/Android_studio.svg';
import Apache_cassandra from './assets/image/stacklogo/Apache_cassandra.svg';
import Apache_kafka from './assets/image/stacklogo/Apache_kafka.svg';
import Apache_spark from './assets/image/stacklogo/Apache_spark.svg';
import Aws from './assets/image/stacklogo/AWS.svg';
import Clang from './assets/image/stacklogo/C.svg';
import Cpp from './assets/image/stacklogo/C++.svg';
import CSharp from './assets/image/stacklogo/C#.svg';
import Django from './assets/image/stacklogo/Django.svg';
import Docker from './assets/image/stacklogo/Docker.svg';
import Express from './assets/image/stacklogo/Express.svg';
import Fastapi from './assets/image/stacklogo/Fastapi.svg';
import Firebase from './assets/image/stacklogo/Firebase.svg';
import Flask from './assets/image/stacklogo/Flask.svg';
import Flutter from './assets/image/stacklogo/Flutter.svg';
import Github_actions from './assets/image/stacklogo/Github_actions.svg';
import Go from './assets/image/stacklogo/Go.svg';
import GraphQL from './assets/image/stacklogo/GraphQL.svg';
import Java from './assets/image/stacklogo/Java.svg';
import Jenkins from './assets/image/stacklogo/Jenkins.svg';
import Julia from './assets/image/stacklogo/Julia.svg';
import Kotlin from './assets/image/stacklogo/Kotlin.svg';
import Kubernetes from './assets/image/stacklogo/Kubernetes.svg';
import Mongodb from './assets/image/stacklogo/Mongodb.svg';
import Mysql from './assets/image/stacklogo/Mysql.svg';
import Nextjs from './assets/image/stacklogo/Nextjs.svg';
import Nodejs from './assets/image/stacklogo/Nodejs.svg';
import Nestjs from './assets/image/stacklogo/Nestjs.svg';
import Php from './assets/image/stacklogo/Php.svg';
import Python from './assets/image/stacklogo/Python.svg';
import PyTorch from './assets/image/stacklogo/PyTorch.svg';
import React from './assets/image/stacklogo/React.svg';
import React_native from './assets/image/stacklogo/React_native.svg';
import Redux from './assets/image/stacklogo/Redux.svg';
import Redis from './assets/image/stacklogo/Redis.svg';
import Rust from './assets/image/stacklogo/Rust.svg';
import Spring from './assets/image/stacklogo/Spring.svg';
import Svelte from './assets/image/stacklogo/Svelte.svg';
import Swift from './assets/image/stacklogo/Swift.svg';
import TensorFlow from './assets/image/stacklogo/TensorFlow.svg';
import TypeScript from './assets/image/stacklogo/TypeScript.svg';
import Unity from './assets/image/stacklogo/Unity.svg';
import Vue from './assets/image/stacklogo/Vue.svg';

class Stack {
  name: string;
  image: string;
  constructor(name: string, image: string) {
    this.name = name;
    this.image = image;
  }
}

const android_studio = new Stack('Android Studio', Android_studio);
const apache_cassandra = new Stack('Apache Cassandra', Apache_cassandra);
const apache_kafka = new Stack('Apache Kafka', Apache_kafka);
const apache_spark = new Stack('Apache Spark', Apache_spark);
const aws = new Stack('AWS', Aws);
const clang = new Stack('C', Clang);
const cpp = new Stack('C++', Cpp);
const csharp = new Stack('C#', CSharp);
const django = new Stack('Django', Django);
const docker = new Stack('Docker', Docker);
const express = new Stack('Express', Express);
const fastapi = new Stack('FastAPI', Fastapi);
const firebase = new Stack('Firebase', Firebase);
const flask = new Stack('Flask', Flask);
const flutter = new Stack('Flutter', Flutter);
const github_actions = new Stack('Github actions', Github_actions);
const go = new Stack('Go', Go);
const graphql = new Stack('GraphQL', GraphQL);
const java = new Stack('Java', Java);
const jenkins = new Stack('Jenkins', Jenkins);
const julia = new Stack('Julia', Julia);
const kotlin = new Stack('Kotlin', Kotlin);
const kubernetes = new Stack('Kubernetes', Kubernetes);
const mongodb = new Stack('MongoDB', Mongodb);
const mysql = new Stack('MYSQL', Mysql);
const nextjs = new Stack('Nextjs', Nextjs);
const nodejs = new Stack('Nodejs', Nodejs);
const nestjs = new Stack('Nestjs', Nestjs);
const php = new Stack('php', Php);
const python = new Stack('Python', Python);
const pytorch = new Stack('PyTorch', PyTorch);
const react = new Stack('React', React);
const react_native = new Stack('ReactNative', React_native);
const redux = new Stack('Redux', Redux);
const redis = new Stack('Redis', Redis);
const rust = new Stack('Rust', Rust);
const spring = new Stack('Spring', Spring);
const svelte = new Stack('Svelte', Svelte);
const swift = new Stack('Swift', Swift);
const tensorflow = new Stack('TensorFlow', TensorFlow);
const typescript = new Stack('TypeScript', TypeScript);
const unity = new Stack('Unity', Unity);
const vue = new Stack('Vue', Vue);

export default Stack;
